git rm .travis.yml
- This repo uses GitHub Actions now, and Travis is [no longer a
  supported CI system to run `brew test-bot`
  with](https://github.com/Homebrew/homebrew-test-bot/pull/312).
- Also, the Travis build fails every time in my fork of this repo with
  the following error:

```
$ rvm use system --install --binary --fuzzy
17.10s$ gem install bundler -v '< 2'
Fetching: bundler-1.17.3.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /var/lib/gems
The command "gem install bundler -v '< 2'" failed and exited with 1 during .
```