trinity 2.11.0 (#1090)
* depends on autotools
* fix error: 'string' is not a member of 'std'
* add license
* use cxx11
* delete version stanza since brew supports this version scheme now