Remove python@2 from gatk formula
Current usage of brew install brewsci/bio/gatk install (for me, on linuxbrew, not sure on mac)

```
==> Installing gatk from brewsci/bio
Error: No available formula with the name "python@2" (dependency of brewsci/bio/gatk)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

python@2 was deleted from homebrew/core in commit 8f8f34572d:
  python@2: delete
  Closes https://github.com/Homebrew/linuxbrew-core/issues/20091.
  Signed-off-by: Michka Popoff <michkapopoff@gmail.com>

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show 8f8f34572d^:Formula/python@2.rb

If you still use this formula consider creating your own tap:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

```

This change simply removes this python dependency. Basic usage of gatk does not cause me trouble and install passed after brew editing this change into the formula